name: Render README

on:
  push:
    branches: [main]
    paths: ["README.Rmd"]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: Rlib

    steps:
      # --- Checkout source with full history ---
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # --- R & Pandoc setup ---
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # --- Prepare library path ---
      - name: Create R library path
        run: mkdir -p Rlib

      # --- Cache installed R packages ---
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: Rlib
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # --- Install system libraries (for packages with compiled code) ---
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libssh2-1-dev \
            libxml2-dev \
            zlib1g-dev \
            libv8-dev \
            cargo \
            libjpeg-dev \
            libpng-dev \
            libmagick++-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev

      # --- Install minimal CRAN packages ---
      - name: Install base R packages
        run: |
          Rscript -e '.libPaths("Rlib");
                      install.packages(
                        c("rmarkdown", "knitr", "remotes", "devtools"),
                        repos = "https://cloud.r-project.org"
                      )'

      # --- Install powergene from GitHub using devtools and PAT ---
      - name: Install powergene from GitHub
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          Rscript -e '.libPaths("Rlib");
                      Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"));
                      if (!requireNamespace("powergene", quietly = TRUE)) {
                        devtools::install_github("akipingu/powergene")
                      }'

      # --- Render README ---
      - name: Render README
        run: |
          Rscript -e '.libPaths("Rlib");
                      rmarkdown::render("README.Rmd", output_format = "md_document")'

      # --- Pull and push rendered README via HTTPS ---
      - name: Pull and push rendered README
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git fetch origin
          git checkout main
          git pull origin main --rebase
          git add README.md
          git commit -m 'Auto-render README.Rmd' || echo "No changes to commit"
          git push origin main
