name: Render README

on:
  push:
    branches:
      - main
    paths:
      - README.Rmd
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: Rlib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Create R library path
        run: mkdir -p Rlib

      # Install system dependencies for packages that need compilation
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libssh2-1-dev \
            build-essential \
            libxml2-dev \
            zlib1g-dev

      # Install all required R packages, including devtools + its deps
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(
              c("rmarkdown","knitr","ggplot2","dplyr","tidyr",
                "curl","gert","gh","usethis","pkgdown","devtools"),
              repos = "https://cloud.r-project.org",
              dependencies = TRUE
          )'

      - name: Install powergene from GitHub
        run: Rscript -e '.libPaths("Rlib"); devtools::install_github("akipingu/powergene")'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'

      - name: Commit rendered README
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Auto-render README.Rmd' || echo "No changes to commit"
          git push
