name: Render README

on:
  push:
    branches:
      - main
    paths:
      - README.Rmd
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: Rlib  # Ensures R uses this path for all packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Create R library path
        run: mkdir -p Rlib

      - name: Install required R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "ggplot2", "dplyr", "tidyr"), repos = "https://cloud.r-project.org")'

      - name: Install devtools and dependencies
        run: Rscript -e 'install.packages(c("devtools", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"), repos = "https://cloud.r-project.org")'

      - name: Install powergene from GitHub
        run: Rscript -e '.libPaths("Rlib"); library(devtools); install_github("akipingu/powergene")'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'

      - name: Commit rendered README
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Auto-render README.Rmd' || echo "No changes to commit"
          git push
